version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo "Build phase started"
      - echo "No build commands required for static website"
artifacts:
  files:
    - '**/*'
